server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:xxx@tcp(xxx:3306)/db03?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: xxx:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2020-01-01"
  machine_id: 1